### ISSUE TITLE
Remove calls to unwrap

### ISSUE THREAD

**Issue by vbrandl** [frewsxcv/rust-notifica#7]
(From my comment on reddit and as a reminder for myself)
You might want to change the notify method to return a `Result<(), SomeErrorType>` and don't call `unwrap()` in your code. It is considered bad practice for a library to panic.

**Comment by frewsxcv** [comment]
I started working on this ([here's the branch](https://github.com/frewsxcv/rust-notifica/pull/new/result)), but a little blocked on moving forward because the `winrt` crate errors [don't implement `Error`](https://github.com/contextfree/winrt-rust/issues/69)

**Comment by vbrandl** [comment]
I missed your comment here and implemented it already.

I implemented a new Error type for `rust-notifica`, which wraps the external error types. I could not test it on Windows, but maybe you can.

**Comment by frewsxcv** [comment]
reopening – we still have a few unwrap calls we need to remove

**Comment by Absolucy** [comment]
These two unwraps _WILL_ panic on macOS if `notify` is used more than once: https://github.com/frewsxcv/rust-notifica/blob/master/src/lib.rs#L177-L178

set_application should be run within a `std::sync::Once`.
